# .github/workflows/build-and-release.yml

name: Build and Push Self-Contained Docker Image

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 */3 * *'

jobs:
  # We now have only one job
  build-and-push:
    name: Build Artifacts and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      # We only need permission to push the package (Docker image) now
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # STEP 1: Build the data artifacts. This creates the 'artifacts' directory.
      - name: Run the full artifact build script
        run: python build_database.py

      # STEP 2: Log in to the container registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # STEP 3: Build and push the Docker image, which will now include the artifacts.
      - name: Build and push self-contained Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
