# .github/workflows/build-and-release.yml

name: Build and Push Self-Contained Docker Image

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 */3 * *'

jobs:
  build-and-push:
    name: Build Artifacts and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the full artifact build script
        # Set the environment variable for the build script
        env:
          PRIORITY_REGIONS: IN,US,UK,KR,FR,DE,JP,ES,IT
        run: python build_database.py

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push self-contained Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
