# .github/workflows/build-and-release.yml

name: Build Data, Create Release, and Push Docker Image

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 */3 * *'

jobs:
  build-and-release-artifacts:
    name: Build and Release Data Artifacts
    runs-on: ubuntu-latest

    # --- THIS IS THE FIX ---
    # We must explicitly grant the GITHUB_TOKEN the permissions
    # required to create a release.
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the full artifact build script
        run: python build_database.py

      - name: Compress artifacts for release
        run: tar -zcvf data-artifacts.tar.gz -C artifacts .

      - name: Create Release and Upload Artifacts
        uses: softprops/action-gh-release@v1
        with:
          tag_name: data-${{ github.run_number }}
          name: "Data Release ${{ github.run_number }}"
          body: "Automated data build. Contains addon_data.db, cosine_sim.pkl, and enriched_titles.pkl."
          files: data-artifacts.tar.gz

  build-docker-image:
    name: Build and Push Lean Docker Image
    runs-on: ubuntu-latest
    # This job doesn't need write permissions, so we don't add them here.
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
